/**
 * AUTO-GENERATED by scripts/fetch-unsplash.mjs — DO NOT EDIT BY HAND.
 * Photography from Unsplash (https://unsplash.com), hotlinked per the Unsplash API Guidelines.
 * Re-run `npm run fetch:images` to refresh.
 */

export interface UnsplashImage {
  url: string;
  thumb: string;
  alt: string;
  authorName: string;
  authorUrl: string;
}

export const HERO_IMAGES: UnsplashImage[] = [
  {
    "url": "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHx3aG9sZXNhbGUlMjBtYXJrZXQlMjB3YXJlaG91c2UlMjB0cmFkZXxlbnwxfDB8fHwxNzgyODI1NDE5fDA&ixlib=rb-4.1.0&w=3840&q=80&fm=jpg&auto=format&fit=max",
    "thumb": "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHx3aG9sZXNhbGUlMjBtYXJrZXQlMjB3YXJlaG91c2UlMjB0cmFkZXxlbnwxfDB8fHwxNzgyODI1NDE5fDA&ixlib=rb-4.1.0&w=480&h=360&fit=crop&q=70&fm=jpg&auto=format",
    "alt": "brown cardboard boxes on white metal rack",
    "authorName": "CHUTTERSNAP",
    "authorUrl": "https://unsplash.com/@chuttersnap?utm_source=b2b_wholesale_hub&utm_medium=referral"
  },
  {
    "url": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHx3aG9sZXNhbGUlMjBtYXJrZXQlMjB3YXJlaG91c2UlMjB0cmFkZXxlbnwxfDB8fHwxNzgyODI1NDE5fDA&ixlib=rb-4.1.0&w=3840&q=80&fm=jpg&auto=format&fit=max",
    "thumb": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHx3aG9sZXNhbGUlMjBtYXJrZXQlMjB3YXJlaG91c2UlMjB0cmFkZXxlbnwxfDB8fHwxNzgyODI1NDE5fDA&ixlib=rb-4.1.0&w=480&h=360&fit=crop&q=70&fm=jpg&auto=format",
    "alt": "yellow and white plastic box lot",
    "authorName": "Adrian Sulyok",
    "authorUrl": "https://unsplash.com/@sulyok_imaging?utm_source=b2b_wholesale_hub&utm_medium=referral"
  },
  {
    "url": "https://images.unsplash.com/photo-1684695749267-233af13276d0?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHx3aG9sZXNhbGUlMjBtYXJrZXQlMjB3YXJlaG91c2UlMjB0cmFkZXxlbnwxfDB8fHwxNzgyODI1NDE5fDA&ixlib=rb-4.1.0&w=3840&q=80&fm=jpg&auto=format&fit=max",
    "thumb": "https://images.unsplash.com/photo-1684695749267-233af13276d0?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHx3aG9sZXNhbGUlMjBtYXJrZXQlMjB3YXJlaG91c2UlMjB0cmFkZXxlbnwxfDB8fHwxNzgyODI1NDE5fDA&ixlib=rb-4.1.0&w=480&h=360&fit=crop&q=70&fm=jpg&auto=format",
    "alt": "a large warehouse filled with lots of boxes",
    "authorName": "Alberto Rodríguez",
    "authorUrl": "https://unsplash.com/@albertorodriguez?utm_source=b2b_wholesale_hub&utm_medium=referral"
  }
];

export const CATEGORY_IMAGES: Record<string, UnsplashImage[]> = {
  "food-grains": [],
  "textiles": [
    {
      "url": "https://images.unsplash.com/photo-1612287665393-dc4ce7714f88?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1612287665393-dc4ce7714f88?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "pink green blue and yellow textile",
      "authorName": "Pixellion",
      "authorUrl": "https://unsplash.com/@pixellion?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1659605422773-9c797452db53?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1659605422773-9c797452db53?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a box of colorful round objects",
      "authorName": "Burkard Meyendriesch",
      "authorUrl": "https://unsplash.com/@bmeyendriesch?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1681003258654-10f89d4e4753?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1681003258654-10f89d4e4753?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a pile of spools of different colors of thread",
      "authorName": "Tuti Fruti Cahyadi",
      "authorUrl": "https://unsplash.com/@throughthelookingglass?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1782232191606-8e2523a3fe80?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1782232191606-8e2523a3fe80?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Numerous white thread spools arranged on a blue industrial rack.",
      "authorName": "The Ordinary Moments",
      "authorUrl": "https://unsplash.com/@cr029?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1754327247961-4bf20df1b1ba?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1754327247961-4bf20df1b1ba?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Colorful fabrics are neatly stacked and organized.",
      "authorName": "Irham Setyaki",
      "authorUrl": "https://unsplash.com/@setyaki?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1713666122130-ec1cd50ff9f3?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1713666122130-ec1cd50ff9f3?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxjb2xvcmZ1bCUyMGZhYnJpYyUyMHRleHRpbGUlMjByb2xsc3xlbnwxfDJ8fHwxNzgyODI1NDIwfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a close up of a multicolored wall hanging",
      "authorName": "Missy Crow",
      "authorUrl": "https://unsplash.com/@mcm411?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ],
  "beverages": [
    {
      "url": "https://images.unsplash.com/photo-1687966742545-8c4725e29159?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1687966742545-8c4725e29159?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a wooden table topped with bottles of liquid and vegetables",
      "authorName": "Sidral Mundet",
      "authorUrl": "https://unsplash.com/@sidralmundet?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1559847844-e5733090e38c?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1559847844-e5733090e38c?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "person pouring liquid to glass",
      "authorName": "Louis Hansel",
      "authorUrl": "https://unsplash.com/@louishansel?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1752084512570-cf76284c09a3?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1752084512570-cf76284c09a3?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Coffee served with cream and sugar.",
      "authorName": "Gavin Vaz",
      "authorUrl": "https://unsplash.com/@gavinvaz?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1766186629784-6214719cf446?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1766186629784-6214719cf446?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Teapot, cup, book, and autumn leaf on table",
      "authorName": "Stacy",
      "authorUrl": "https://unsplash.com/@stacysuxx?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1686465065467-ad7f1eea65ae?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1686465065467-ad7f1eea65ae?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a person pouring tea into a cup on a picnic table",
      "authorName": "Sergey N",
      "authorUrl": "https://unsplash.com/@tipod?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1750085037147-0f141272a67f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1750085037147-0f141272a67f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHx0ZWElMjBsZWF2ZXMlMjBhbmQlMjBib3R0bGVkJTIwZHJpbmtzfGVufDF8Mnx8fDE3ODI4MjU0MjF8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Soda bottles and cans are stocked on supermarket shelves.",
      "authorName": "Zoshua Colah",
      "authorUrl": "https://unsplash.com/@zoshuacolah?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ],
  "home-kitchen": [
    {
      "url": "https://images.unsplash.com/photo-1597758464605-aa125b827c33?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1597758464605-aa125b827c33?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "yellow lemon on white and green floral ceramic plate",
      "authorName": "Molleni Ceramics",
      "authorUrl": "https://unsplash.com/@molleni?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1660282799218-a70843acca61?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1660282799218-a70843acca61?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a group of colorful plates",
      "authorName": "mana5280",
      "authorUrl": "https://unsplash.com/@mana5280?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1597758198513-e26ffb224a1d?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1597758198513-e26ffb224a1d?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "red apples on white and blue floral ceramic plate",
      "authorName": "Molleni Ceramics",
      "authorUrl": "https://unsplash.com/@molleni?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1662487091262-7aeadeca2024?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1662487091262-7aeadeca2024?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a group of bowls with colorful designs",
      "authorName": "Greg Willson",
      "authorUrl": "https://unsplash.com/@gregwillson?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1625123423088-485b41e7618c?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1625123423088-485b41e7618c?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "white ceramic teacup on brown wooden table",
      "authorName": "俊瑋 王",
      "authorUrl": "https://unsplash.com/@wl001002631?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1622845531094-100fbf39300d?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1622845531094-100fbf39300d?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxjZXJhbWljJTIwcGxhdGVzJTIwa2l0Y2hlbndhcmV8ZW58MXwyfHx8MTc4MjgyNTQyMnww&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "black and white ceramic bowl",
      "authorName": "Brian Alatorre",
      "authorUrl": "https://unsplash.com/@brianalatorre?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ],
  "eco-packaging": [
    {
      "url": "https://images.unsplash.com/photo-1641357497181-94a7ce5a3d7b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1641357497181-94a7ce5a3d7b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a pile of pillows sitting on top of each other",
      "authorName": "Derek Phan",
      "authorUrl": "https://unsplash.com/@phanvuthanhtoan?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1642429947946-cccdb64cb67b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1642429947946-cccdb64cb67b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a bag of coffee sitting on top of a blanket",
      "authorName": "everdrop GmbH",
      "authorUrl": "https://unsplash.com/@everdrop?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1563117975-6c407a45f21f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1563117975-6c407a45f21f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "coffee beans on brown sack",
      "authorName": "Anthony Espinosa",
      "authorUrl": "https://unsplash.com/@thony_espi?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1615485925706-8f0289e9f11c?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1615485925706-8f0289e9f11c?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "brown and white heart shaped pillow",
      "authorName": "Mockup Graphics",
      "authorUrl": "https://unsplash.com/@mockupgraphics?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1560579184-d098f5fbfae8?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1560579184-d098f5fbfae8?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "man in gray robe sitting on the stack of socks",
      "authorName": "Eugene Nelmin",
      "authorUrl": "https://unsplash.com/@nelmin?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1767281076175-e52ca45cb2d9?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1767281076175-e52ca45cb2d9?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxqdXRlJTIwYmFncyUyMHNhY2tzJTIwcGFja2FnaW5nfGVufDF8Mnx8fDE3ODI4MjU0MjN8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Bundles of dried grass and feathers tied with orange string",
      "authorName": "Bernd 📷 Dittrich",
      "authorUrl": "https://unsplash.com/@hdbernd?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ],
  "electronics": [
    {
      "url": "https://images.unsplash.com/photo-1532007271951-c487760934ae?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1532007271951-c487760934ae?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "white bulb",
      "authorName": "Federico Bottos",
      "authorUrl": "https://unsplash.com/@landscapeplaces?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1712294252418-680891540aa8?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1712294252418-680891540aa8?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a white light bulb on an orange and pink background",
      "authorName": "Jakub Żerdzicki",
      "authorUrl": "https://unsplash.com/@jakubzerdzicki?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1641113403042-0b6f6e5e0a35?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1641113403042-0b6f6e5e0a35?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a white light bulb on a black background",
      "authorName": "nuddle",
      "authorUrl": "https://unsplash.com/@nuddle?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1694009130859-59eaad26099f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1694009130859-59eaad26099f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a colorful light bulb sitting on top of a table",
      "authorName": "Gary Walker-Jones",
      "authorUrl": "https://unsplash.com/@gwj72?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1775830389014-7af767e81007?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1775830389014-7af767e81007?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Various vintage edison light bulbs illuminated indoors",
      "authorName": "Jonathan Lim",
      "authorUrl": "https://unsplash.com/@jonathankslim?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1740126102782-f540f9b9bef4?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1740126102782-f540f9b9bef4?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxsaWdodCUyMGJ1bGJzJTIwZWxlY3Ryb25pY3MlMjBhY2Nlc3Nvcmllc3xlbnwxfDJ8fHwxNzgyODI1NDIzfDA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Three boxes of toothbrushes sitting on a table",
      "authorName": "GB The Green Brand",
      "authorUrl": "https://unsplash.com/@gb_the_green_brand?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ],
  "construction": [
    {
      "url": "https://images.unsplash.com/photo-1557486093-27e8c39d11a4?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1557486093-27e8c39d11a4?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "man carrying white bag",
      "authorName": "kevin Baquerizo",
      "authorUrl": "https://unsplash.com/@kevinbae?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1681822188663-4103ef9124fe?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1681822188663-4103ef9124fe?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a pile of dirt sitting next to a pile of dirt",
      "authorName": "Derek Lee",
      "authorUrl": "https://unsplash.com/@derekleej?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1641357497181-94a7ce5a3d7b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1641357497181-94a7ce5a3d7b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a pile of pillows sitting on top of each other",
      "authorName": "Derek Phan",
      "authorUrl": "https://unsplash.com/@phanvuthanhtoan?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1562118511-e0aa3d7b0373?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1562118511-e0aa3d7b0373?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "person standing near red panel",
      "authorName": "Connor Fisher",
      "authorUrl": "https://unsplash.com/@dafishmaster?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1617906681877-728fa008950b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1617906681877-728fa008950b?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "yellow and black crane near brown wooden house during daytime",
      "authorName": "Alex Plesovskich",
      "authorUrl": "https://unsplash.com/@aples?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1586166005440-ebb2da58432f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1586166005440-ebb2da58432f?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxjZW1lbnQlMjBiYWdzJTIwY29uc3RydWN0aW9uJTIwbWF0ZXJpYWxzfGVufDF8Mnx8fDE3ODI4MjU0MjR8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "white and red metal frame",
      "authorName": "Simone Hutsch",
      "authorUrl": "https://unsplash.com/@heysupersimi?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ],
  "health-beauty": [
    {
      "url": "https://images.unsplash.com/photo-1661450159193-633134194753?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1661450159193-633134194753?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwxfHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a group of cheeses",
      "authorName": "Tarah Dane",
      "authorUrl": "https://unsplash.com/@danesvg?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1661450159298-d58a3b98f3a4?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1661450159298-d58a3b98f3a4?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwyfHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a group of hot dogs in a baking dish",
      "authorName": "Tarah Dane",
      "authorUrl": "https://unsplash.com/@danesvg?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1704307068094-c2c88c467014?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1704307068094-c2c88c467014?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHwzfHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a bottle of lotion sitting on top of a table",
      "authorName": "shashank singh",
      "authorUrl": "https://unsplash.com/@mrsagartech?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1672330427989-7676be4a34bc?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1672330427989-7676be4a34bc?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw0fHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "a couple of items that are on a table",
      "authorName": "Akky Vaishnav",
      "authorUrl": "https://unsplash.com/@akkyvaishnav?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1758788390320-16e1f280cf49?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1758788390320-16e1f280cf49?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw1fHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Various dark bottles and jars of skincare products.",
      "authorName": "Ela De Pure",
      "authorUrl": "https://unsplash.com/@eladepure?utm_source=b2b_wholesale_hub&utm_medium=referral"
    },
    {
      "url": "https://images.unsplash.com/photo-1772442934379-21275cb79134?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=900&h=675&fit=crop&q=80&fm=jpg&auto=format",
      "thumb": "https://images.unsplash.com/photo-1772442934379-21275cb79134?ixid=M3w5ODkxNDZ8MHwxfHNlYXJjaHw2fHxzb2FwJTIwY29zbWV0aWNzJTIwcGVyc29uYWwlMjBjYXJlfGVufDF8Mnx8fDE3ODI4MjU0MjV8MA&ixlib=rb-4.1.0&w=320&h=240&fit=crop&q=70&fm=jpg&auto=format",
      "alt": "Hand holding a bottle of hibiscus body lotion.",
      "authorName": "The Good Hygiene Co.",
      "authorUrl": "https://unsplash.com/@thegoodhygieneco?utm_source=b2b_wholesale_hub&utm_medium=referral"
    }
  ]
};
