/** Audit event types recorded for auth/authorization events (Req 19.5, Property 40). */
export const AuthEvent = {
  USER_REGISTERED: 'USER_REGISTERED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  AUTH_REJECTED_LOCKED: 'AUTH_REJECTED_LOCKED',
  AUTH_REJECTED_SUSPENDED: 'AUTH_REJECTED_SUSPENDED',
  AUTH_REJECTED_INACTIVE: 'AUTH_REJECTED_INACTIVE',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  REFRESH_REJECTED: 'REFRESH_REJECTED',
  LOGOUT: 'LOGOUT',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCESS_GRANTED: 'ACCESS_GRANTED',
  ACCESS_DENIED: 'ACCESS_DENIED',
} as const;

export type AuthEventType = (typeof AuthEvent)[keyof typeof AuthEvent];
