package com.b2bwholesalehub.inventory.common;

/** Stable, machine-readable error codes surfaced in the shared error envelope. */
public enum ErrorCode {
  VALIDATION_ERROR,
  PRICING_VALIDATION_ERROR,
  TIER_RANGE_ERROR,
  TIER_QUANTITY_ERROR,
  TIER_PRICE_ERROR,
  TIER_OVERLAP,
  STOCK_VALIDATION_ERROR,
  RESERVATION_QUANTITY_ERROR,
  NOT_FOUND,
  FORBIDDEN,
  CONFLICT,
  PUBLISH_NOT_VERIFIED,
  MOQ_NOT_MET,
  INSUFFICIENT_STOCK,
  EMPTY_CART,
  RESERVATION_EXPIRED,
  INVALID_TRANSITION,
  REVIEW_NOT_ELIGIBLE,
  REVIEW_ALREADY_EXISTS,
  REVIEW_RATING_ERROR,
  INTERNAL_ERROR
}
